### ISSUE TITLE
document the target multi-device semantics

### ISSUE THREAD

**Issue by DustinWehr** [DougReeder/notes-together#1]
It seems the app doesn't attempt to merge when changes are made to the same document from two offline devices, and then the devices come back online And that is perfectly fine! But I think it would be great if there was a note on your help page about any limitations of sync, so users aren't surprised.

**Comment by DougReeder** [comment]
There is code to merge conflicts... but it didn't work well enough, so it's disabled. :-(  Good point that the behavior needs to be documented.

**Comment by DougReeder** [comment]
Documented by commit a8654e50a1892c36dde7e89b3456b364a11c1d60
